package io.project.clientkeeperbot.state;

public enum BotState {
    // Состояния для пользователей
    START,
    WAITING_CAPTCHA,
    MAIN_MENU,

    // Состояния для администраторов
    AWAITING_COMMENT,
    DEFAULT,

    ENTER_CUSTOM_PROJECT_TYPE,
    CONFIRM_CANCEL,


    CHART_PERIOD_SELECTION,
    CHART_CUSTOM_DATE_FROM,
    CHART_CUSTOM_DATE_TO,
    ENTER_CHART_PERIOD,

    CHART_CUSTOM_DATE_FROM_ADMIN,
    CHART_CUSTOM_DATE_TO_ADMIN,
    ENTER_CHART_PERIOD_ADMIN,

    ATTACHMENT_WAITING_FILE, // ожидание, что пользователь отправит файл
    ASK_ATTACHMENTS_DECISION,
    ASK_ATTACHMENTS,
    WAITING_FOR_ATTACHMENTS,

    EDIT_PROJECT_TYPE,
    EDIT_DESCRIPTION,
    EDIT_DEADLINE,
    EDIT_BUDGET,
    EDIT_CONTACT,

    ASK_PROJECT_TYPE,
    ASK_DESCRIPTION,
    ASK_DEADLINE,
    ASK_BUDGET,
    ASK_CONTACT,
    REVIEW_DRAFT,

}